#include <stdio.h>

/**
 * Code for io library in Simple Language
 * Llvm code for this library is generated by clang using
 *
 * ```
 * clang -emit-llvm -S ioLibrary.c
 * ```
 */
int readInt() {
	int i;
	scanf("%d", &i);
	char c;
	while((c = getchar()) != EOF && c != '\n'); 
	return i;
}

double readReal() {
	double i;
	scanf("%lf", &i);
	char c;
	while((c = getchar()) != EOF && c != '\n'); 
	return i;
}

int writeInt(int x) {
	return printf("%d\n", x);
}

int writeReal(double x) {
	return printf("%lf\n", x);
}

